package at.ppmrob.examples.main;

public enum LastKnownCircleLinePosition {
	LEFT_RECTANGLE_UPPER_HLAF,
	LEFT_RECTANGLE_BOTTOM_HLAF,
	
	RIGHT_RECTANGLE_UPPER_HLAF,
	RIGHT_RECTANGLE_BOTTOM_HLAF,
	
	CENTER_RECTANGLE_UPPER_HLAF,
	CENTER_RECTANGLE_BOTTOM_HLAF,
	
}
