package at.ppmrob.examples.main;

public enum LastKnownCircleLinePosition {
	LEFT_RECTANGLE_UPPER_HLAF,
	LEFT_RECTANGLE_BOTTOM_HLAF,
	
	RIGHT_RECTANGLE_UPPER_HLAF,
	RIGHT_RECTANGLE_BOTTOM_HLAF,
	
	CENTER_RECTANGLE_UPPER_HLAF,
	CENTER_RECTANGLE_BOTTOM_HLAF,
	
	CENTER_UP_AND_BOTTOM,
	
	LEFT_UP_AND_BOTTOM,
	
	RIGHT_UP_AND_BOTTOM,
	
	

	
	CENTER_UP_AND_RIGHT_BOTTOM,
	
	CENTER_UP_AND_LEFT_BOTTOM,
	
	LEFT_UP_AND_CENTER_OR_RIGHT,
	
	RIGHT_UP_AND_CENTER_OR_LEFT
	
}
