package at.ppmrob.autopilot.state;

public enum AutoPilotState {
	DRONE_ON_GROUND,
	DRONE_TAKEOFF,
	DRONE_IS_FLYING,
	DRONE_STAY_OVER_STARTING_CIRCLE,
	DRONE_STAY_OVER_LINE,
	DRONE_STAY_OVER_FINISH_CIRCLE,
	DRONE_TURN_360,
	DRONE_FOLLOW_LINE,
	DRONE_LAND,
	DRONE_LOST_CIRCLE,
	DRONE_LOST_LINE
}
